name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight UTC
  workflow_dispatch:    # lets you trigger it manually

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Snake GIF and SVG
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Yozora13
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "ğŸ Update snake animation"
          add: "output/*.svg"
